<?php
add_action('init', function () {
    if (isset($_SERVER['REQUEST_URI']) && preg_match('#^/llms\.txt$#', $_SERVER['REQUEST_URI'])) {
        ssseo_output_llms();
        exit;
    }
});

function ssseo_output_llms() {
    header('Content-Type: text/plain');
    echo ssseo_output_llms_to_string();
    exit;
}

function ssseo_output_llms_to_string() {
    return ssseo_build_llms_txt();
}

function ssseo_build_llms_txt() {
    $output = [];

    // === ORGANIZATION FIELDS FROM PLUGIN ===
    $org_url         = get_option('ssseo_org_url', home_url('/'));
    $org_name        = get_option('ssseo_org_name', '');
    $org_legal_name  = get_option('ssseo_org_legal_name', '');
    $org_desc        = get_option('ssseo_org_description', '');
    $org_logo        = get_option('ssseo_org_logo', '');
    $org_email       = get_option('ssseo_org_email', get_option('admin_email'));
    $org_phone       = get_option('ssseo_org_phone', '');
    $org_founded     = get_option('ssseo_org_founding_date', '');
    $org_social      = (array) get_option('ssseo_org_social', []);
    $org_hours       = (array) get_option('ssseo_org_hours', []);

    // === FETCH SCHEMA IF PLUGIN FIELDS ARE EMPTY ===
    $schema = [];
    if (empty($org_name) || empty($org_legal_name) || empty($org_logo) || empty($org_desc) || empty($org_phone)) {
        $schema = ssseo_fetch_schema_from_url($org_url);
    }

    if (!empty($schema['Organization'])) {
        $orgSchema = $schema['Organization'];

        if (empty($org_name)) {
            $org_name = $orgSchema['name'] ?? '';
        }

        if (empty($org_legal_name)) {
            $org_legal_name = $orgSchema['legalName'] ?? ($orgSchema['name'] ?? '');
        }

        if (empty($org_logo)) {
            if (is_array($orgSchema['logo']) && isset($orgSchema['logo']['url'])) {
                $org_logo = $orgSchema['logo']['url'];
            } elseif (is_string($orgSchema['logo'])) {
                $org_logo = $orgSchema['logo'];
            }
        }

        if (empty($org_desc)) {
            $org_desc = $orgSchema['description'] ?? '';
        }

        if (empty($org_social) && !empty($orgSchema['sameAs'])) {
            $org_social = is_array($orgSchema['sameAs']) ? $orgSchema['sameAs'] : [$orgSchema['sameAs']];
        }
    }

    // === META DESCRIPTION FALLBACK ===
    if (empty($org_desc)) {
        $meta_desc = ssseo_extract_meta_description($org_url);
        if (!empty($meta_desc)) {
            $org_desc = $meta_desc;
        }
    }

    // === LOCATIONS — MULTI-SCHEMA SUPPORT ===
    $locations = [];

    if (!empty($schema['LocalBusiness'])) {
        $schemaLocations = is_array($schema['LocalBusiness']) && isset($schema['LocalBusiness'][0])
            ? $schema['LocalBusiness']
            : [$schema['LocalBusiness']];

        foreach ($schemaLocations as $loc) {
            $locations[] = [
                'location_name'  => $loc['name'] ?? 'Office',
                'street_address' => $loc['address']['streetAddress'] ?? '',
                'locality'       => $loc['address']['addressLocality'] ?? '',
                'region'         => $loc['address']['addressRegion'] ?? '',
                'postal_code'    => $loc['address']['postalCode'] ?? '',
                'country'        => $loc['address']['addressCountry'] ?? '',
                'latitude'       => $loc['geo']['latitude'] ?? '',
                'longitude'      => $loc['geo']['longitude'] ?? '',
                'phone'          => $loc['telephone'] ?? '',
                'opening_hours'  => ssseo_parse_opening_hours($loc['openingHours'] ?? null),
            ];
        }

        // Fallback phone from first LocalBusiness
        if (empty($org_phone)) {
            foreach ($locations as $loc) {
                if (!empty($loc['phone'])) {
                    $org_phone = $loc['phone'];
                    break;
                }
            }
        }
    }

    if (empty($locations)) {
        $locations = get_option('ssseo_localbusiness_entries', []);
    }

    // === SERVICES ===
    $services = get_posts([
        'post_type'      => 'service',
        'post_status'    => 'publish',
        'posts_per_page' => -1,
        'orderby'        => 'title',
        'order'          => 'ASC',
    ]);

    $service_areas = get_posts([
        'post_type'      => 'service_area',
        'post_status'    => 'publish',
        'posts_per_page' => -1,
        'orderby'        => 'title',
        'order'          => 'ASC',
    ]);

    // === OUTPUT ===
    $output[] = "# llms.txt dynamically generated by ssseo-tools";
    $output[] = "version: 1.0\n";

    $output[] = "organization:";
    if (!empty($org_name))        $output[] = "  name: {$org_name}";
    if (!empty($org_legal_name))  $output[] = "  legal_name: {$org_legal_name}";
    $output[] = "  url: {$org_url}";
    if (!empty($org_logo))        $output[] = "  logo: {$org_logo}";
    if (!empty($org_desc))        $output[] = "  description: {$org_desc}";
    $output[] = "  email: {$org_email}";
    $output[] = "  phone: {$org_phone}";
    $output[] = "  founding_date: {$org_founded}";
    $output[] = "  is_local: true\n";

    $output[] = "locations:";
    foreach ($locations as $loc) {
        $output[] = "  - name: " . ($loc['location_name'] ?? 'Office');
        $output[] = "    address: " . ($loc['street_address'] ?? '');
        $output[] = "    locality: " . ($loc['locality'] ?? '');
        $output[] = "    region: " . ($loc['region'] ?? '');
        $output[] = "    postal_code: " . ($loc['postal_code'] ?? '');
        $output[] = "    country: " . ($loc['country'] ?? 'US');
        $output[] = "    latitude: " . ($loc['latitude'] ?? '');
        $output[] = "    longitude: " . ($loc['longitude'] ?? '');
        $output[] = "    phone: " . ($loc['phone'] ?? $org_phone);
        $output[] = "";
    }

    $output[] = "services:";
    foreach ($services as $svc) {
        $output[] = "  - name: {$svc->post_title}";
    }

    $output[] = "service_areas:";
    foreach ($service_areas as $area) {
        $output[] = "  - name: {$area->post_title}";
    }

    $output[] = "\nlanguages:\n  - en";
    $output[] = "audience:\n  - individuals\n  - local customers\n  - professionals";
    $output[] = "accessibility:\n  wheelchair_accessible: true\n  ada_compliant: true";

    $hours = $locations[0]['opening_hours'] ?? $org_hours;
    if (!empty($hours)) {
        $output[] = "hours:";
        foreach ($hours as $entry) {
            $day = strtolower($entry['day'] ?? '');
            $opens = $entry['opens'] ?? '';
            $closes = $entry['closes'] ?? '';
            if ($day && $opens && $closes) {
                $output[] = "  {$day}: {$opens}-{$closes}";
            }
        }
    }

    if (!empty($org_social)) {
        $output[] = "social_profiles:";
        foreach ($org_social as $url) {
            $output[] = "  - {$url}";
        }
    }

    $output[] = "\nai_usage:";
    $output[] = "  ai_chat_compatible: true";
    $output[] = "  accepts_ai_contact: true";
    $output[] = "  chatbot_url:";

    return implode("\n", $output);
}

// === SCHEMA PARSER ===
function ssseo_fetch_schema_from_url($url) {
    $resp = wp_remote_get($url);
    if (is_wp_error($resp) || wp_remote_retrieve_response_code($resp) !== 200) return [];

    $html = wp_remote_retrieve_body($resp);
    if (!preg_match_all('/<script type=["\']application\/ld\+json["\']>(.*?)<\/script>/is', $html, $matches)) {
        return [];
    }

    $data = [];
    foreach ($matches[1] as $json) {
        $obj = json_decode(trim($json), true);
        if (!$obj) continue;
        $items = isset($obj['@type']) ? [$obj] : ($obj['@graph'] ?? []);
        foreach ($items as $item) {
            $type = $item['@type'] ?? '';
            if (in_array($type, ['Organization', 'LocalBusiness'], true)) {
                if (!isset($data[$type])) $data[$type] = [];
                $data[$type][] = $item;
            }
        }
    }

    foreach (['Organization', 'LocalBusiness'] as $type) {
        if (isset($data[$type]) && count($data[$type]) === 1) {
            $data[$type] = $data[$type][0];
        }
    }

    return $data;
}

// === META DESCRIPTION PARSER ===
function ssseo_extract_meta_description($url) {
    $resp = wp_remote_get($url);
    if (is_wp_error($resp) || wp_remote_retrieve_response_code($resp) !== 200) return '';
    $html = wp_remote_retrieve_body($resp);
    if (preg_match('/<meta\s+name=["\']description["\']\s+content=["\']([^"\']+)["\']/i', $html, $matches)) {
        return trim($matches[1]);
    }
    return '';
}

// === HOURS FORMATTER ===
function ssseo_parse_opening_hours($input) {
    if (!$input) return [];
    $lines = is_array($input) ? $input : explode("\n", $input);
    $result = [];

    foreach ($lines as $line) {
        if (preg_match('/^(?P<days>[A-Za-z,\-]+)\s+(?P<times>\d{2}:\d{2}-\d{2}:\d{2})$/', trim($line), $m)) {
            [$opens, $closes] = explode('-', $m['times']);
            foreach (explode(',', $m['days']) as $d) {
                $d = strtolower(trim($d));
                $result[] = [
                    'day' => $d,
                    'opens' => $opens,
                    'closes' => $closes,
                ];
            }
        }
    }

    return $result;
}
